### ISSUE TITLE
本地已经登录qq了，运行脚本提示请求失败，请先登录电脑QQ

### ISSUE THREAD

**Issue by Th0m4z-sec** [Equinox-shame/QQ_Steal_Skey#1]
本地已经登录qq了，运行脚本提示请求失败，请先登录电脑QQ，求大佬解答

**Comment by Equinox-shame** [comment]
登录的QQ是什么版本呢，可能最新版本的QQ无法适配？

**Comment by lonelyxmas** [comment]
已失效?

**Comment by Equinox-shame** [comment]
> 已失效?

![image](https://github.com/Equinox-shame/QQ_Steal_Skey/assets/59494794/00792706-2117-48ae-8073-42c2ee01b98c)

经过测试没有失效啊，可以看看QQ的版本信息，可能在高版本上此方法会失效，具体我没验证过

**Comment by Equinox-shame** [comment]
>  已失效?

![image](https://private-user-images.githubusercontent.com/59494794/308515456-00792706-2117-48ae-8073-42c2ee01b98c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTY4ODMsIm5iZiI6MTcwOTExNjU4MywicGF0aCI6Ii81OTQ5NDc5NC8zMDg1MTU0NTYtMDA3OTI3MDYtMjExNy00OGFlLTgwNzMtNDJjMmVlMDFiOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDEwMzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDhmNGYzYzJmNWE1MTFhYTg0OWU3Yzc5Zjk4MjQ2MzNkMjA2YjRjZWRjYjExNzAxMjgxNGIyNGU4NmUwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9IAGvJXK0eRnHdu1RkOnBMCjgTE8bV_iYW9QLnNo4ro)

经过测试没有失效啊，可以看看QQ的版本信息，可能在高版本上此方法会失效，具体我没验证过

**Comment by Equinox-shame** [comment]
![image](https://github.com/Equinox-shame/QQ_Steal_Skey/assets/59494794/0d047b7c-918c-4cd0-9f37-ce08f9523936)

**Comment by Equinox-shame** [comment]
@Th0m4z-sec @lonelyxmas

**Comment by lonelyxmas** [comment]
![图片](https://github.com/Equinox-shame/QQ_Steal_Skey/assets/836377/33e05893-92f6-4fd3-b547-7293591bd2a6)

**Comment by Equinox-shame** [comment]
> ![图片](https://private-user-images.githubusercontent.com/836377/309530437-33e05893-92f6-4fd3-b547-7293591bd2a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTQwMTMsIm5iZiI6MTcwOTQ1MzcxMywicGF0aCI6Ii84MzYzNzcvMzA5NTMwNDM3LTMzZTA1ODkzLTkyZjYtNGZkMy1iNTQ3LTcyOTM1OTFiZDJhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwODE1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzhiMTdkOTAwNDM1OTQzNjRmMjkyOGJiYjEwMjEyODgwYjdlMWM0YTE3ZjdiNWEyZDUzMTQ1MGQ5MDY5MjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._NxAsGxxH4FqW3Jn6NUkOb2yekPagnN_Vh0_8BWfH30)

@lonelyxmas 经过测试QQ9.7.22版本对应方法已经失效，对应解决方法可以考虑降级QQ版本到ReadMe中测试的版本
