### ISSUE TITLE
我知道获取思路,请问作者需要吗(点开看)

### ISSUE THREAD

**Issue by sun589** [Equinox-shame/QQ_Steal_Skey#2]
我自己钻研了一个,也是快捷登录的
详见 https://github.com/sun589/QQkey_Tool
可供参考

**Comment by sun589** [comment]
QQ 9.9.15正常获取

**Comment by Equinox-shame** [comment]
感谢分享

**Comment by sun589** [comment]
> 感谢分享

不用谢,需要的话不妨点个star,这些技术外面都要收费
